config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }


  #get 'users/show'
  resources :users,               only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # deviseコントローラーによる追加
  # devise_for :users, controllers: {
  # sessions: 'users/sessions',
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  # registrations: 'users/registrations'
  # }
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    @q = Micropost.ransack(params[:q])
    @microposts = @q.result(distinct: true).page(params[:page]).per(9)
    # @microposts =Kaminari.paginate_array(Micropost.all).page(params[:page]).per(9)
  end

  def index
    @q = Micropost.ransack(params[:q])
    if params[:tags_name]
      @microposts = @q.result(distinct: true).tagged_with("#{params[:tags_name]}").page(params[:page]).per(9)
    else
      @microposts = @q.result(distinct: true).page(params[:page]).per(9)
    end
    #if params[:tag_name]
      #@microposts = Micropost.tagged_with("#{params[:tag_name]}").page(params[:page]).per(9)
    #end
    @tags = Micropost.tag_counts.group(:name).order('taggings_count DESC').limit(5)
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/_home_microposts.html.erb
<div class="row">
<div class="col-md-12">
<div class="card-group">
  <% @microposts.each do |micropost| %>
<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
        <%=link_to image_tag(micropost.picture.url,class:'bd-placeholder-img card-img-top' , size: '300x225'),micropost if micropost.picture? %>
    <div class="card-body">
      <p class="card-content"><%= micropost.content %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to micropost.user.name, micropost.user ,class: 'text-dark ml-2 mt-1 ml-sm-0',role: 'button'%>
          
          <!--いいね機能を追加-->
            <span class="float-right ml-2 d-none d-sm-block" id="micropost-<%= micropost.id %>">
              <%= render "likes/like", micropost: micropost %>
            </span>
          <!-- ------------------------------------------------  -->

            <span class="ml-4 mt-1 text-muted  d-sm-block d-none"><%= micropost.created_at.strftime("%m/%d %H:%M") %></span>
              
        </div>
      </div>
  
      <%= render 'shared/tag_list', tag_list: micropost.tag_list %>

    </div>
  </div>
</div>
<% end %>
</div>

<%= paginate @microposts %>

</div>
</div>

app/views/static_pages/_logged_in_home.html.erb
<!--ログイン後の画面-->
<div class =row>
<div class ="container pt-5 col-xs-12">
  <div class="jumbotron">
   <%= link_to "#{current_user.name}さん", user_path(current_user),class: 'display-4 text-dark'%>
   <p class="lead">あなたのお気に入りの料理をみんなで共有しよう。そうすれば世界が広がるはずです。</p>
 </div>
</div>
   
   <div class="container mt-5">

     <h1 class="text-center pb-3">Food Phots</h1>
      <!--検索機能-->
       <div class ="text-center">
        <%= search_form_for(@q,url: static_pages_home_path, method: :get) do |f| %>
        <%= f.search_field :content_or_tags_name_cont, placeholder: "キーワードで検索" %>
          <%= button_tag type: 'submit',class: 'btn btn-dark mb-1' do %>
           <i class="fas fa-search"></i>
          <% end %>
       <%end%>
       
       <%= link_to "タグ詳細", static_pages_index_path, class: 'text-dark' %>

      </div>

    <div class = "mt-5">
      <%=render "home_microposts" %>
    </div>
   </div>
   </div>

app/views/static_pages/_not__logged_in_home.html.erb
<!--ログイン前の画面-->
<div class =row>
<div class ="container pt-5 col-xs-12">
  <div class="jumbotron">
   <h1 class="display-4">ようこそ!</h1>
   <p class="lead">あなたのお気に入りの料理をみんなで共有しよう。そうすれば世界が広がるはずです。</p>
   <hr class="my-4">
   <p>さっそく新規登録、ログインをしてサービスを利用しよう。かんたんログイン機能を使えば登録せずにすぐにサービスを活用できます。</p>
   <%= link_to "新規登録", new_user_registration_path ,class: 'btn btn-secondary btn-lg',role: 'button'%>
   <%= link_to "ログイン", new_user_session_path ,class: 'btn btn-secondary btn-lg',role: 'button'%>
 </div>
</div>

  <div class="container mt-5">

    <h1 class="text-center pb-3">Food Phots</h1>
    <!--検索機能-->
       <div class ="text-center">
        <%= search_form_for(@q,url: static_pages_home_path, method: :get) do |f| %>
        <%= f.search_field :content_or_tags_name_cont, placeholder: "キーワードで検索" %>
          <%= button_tag type: 'submit',class: 'btn btn-dark mb-1' do %>
           <i class="fas fa-search"></i>
          <% end %>
       <%end%>
       
       <%= link_to "タグ詳細", static_pages_index_path, class: 'text-dark' %>

      </div>
  </div>

  <div class="container mt-5">

     <%=render "home_microposts" %>
 
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if user_signed_in? %>

  <%=render "logged_in_home" %>

<% else %>

  <%=render "not__logged_in_home" %>

<% end %>

app/views/static_pages/index.html.erb
<% provide(:title, "TAG") %>

<div class="container mt-5">
  <h1 class="text-center pb-3">Trend!!</h1>
  
  <div class = "text-center">
    <%= render 'shared/tag_count', tag_list: @tags %>
  </div>

  
  <!--検索機能-->
       <div class ="text-center mt-5">
        <%= search_form_for(@q,url: static_pages_index_path, method: :get) do |f| %>
        <%= f.search_field :tags_name_cont, placeholder: "タグで検索" %>
          <%= button_tag type: 'submit',class: 'btn btn-dark mb-1' do %>
           <i class="fas fa-search"></i>
          <% end %>
       <%end%>

  <div class = "mt-5">
      <%=render "home_microposts" %>
    </div>

<div>