config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }


  #get 'users/show'
  resources :users,               only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # deviseコントローラーによる追加
  # devise_for :users, controllers: {
  # sessions: 'users/sessions',
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  # registrations: 'users/registrations'
  # }
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
    <ul>
        <% model.errors.full_messages.each do |message| %>
            <li class="pr-5 text-danger"><i class="fas fa-exclamation-triangle"></i><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="container mb-5">

  <a>
  
  <%=link_to "#{@user.following.count}フォロー", following_user_path(@user),class: "btn btn-secondary" %>
    
     
    
  
 
    <span id="followers">
    <%=link_to "#{@user.followers.count}フォロワー", followers_user_path(@user),class: "btn btn-secondary"%>
     </span>
    
    
  </a>
   
</div>

app/views/shared/_tag_count.html.erb
<% tag_list.each do |tag| %>
 <%= link_to tag, static_pages_index_path(tags_name: tag.name),class: 'badge badge-secondary' %>
 <%= "#{tag.taggings_count}回" %>
<% end %>

app/views/shared/_tag_list.html.erb
<% tag_list.each do |tag| %>
 <%= link_to tag, static_pages_index_path(@micropost,tags_name: tag), class: 'badge badge-secondary' %>
<% end %>