config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }


  #get 'users/show'
  resources :users,               only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # deviseコントローラーによる追加
  # devise_for :users, controllers: {
  # sessions: 'users/sessions',
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  # registrations: 'users/registrations'
  # }
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  # 投稿の順序を調整
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :picture, presence: true

  mount_uploader :picture, PictureUploader
  validate :picture_size

  has_many :likes, dependent: :destroy
  has_many :good_users, through: :likes, source: :user
  
  #タグ機能
  acts_as_taggable

  def good(user)
    likes.create(user_id: user.id)
  end

  def ungood(user)
    likes.find_by(user_id: user.id).destroy
  end

  # 現在のユーザーがいいねしてたらtrueを返す
  def good?(user)
    good_users.include?(user)
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, 'should be less than 5MB') if picture.size > 5.megabytes
  end
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :correct_user, only: :destroy

  def new
    @micropost = current_user.microposts.build if user_signed_in?
  end

  def show
    @micropost = Micropost.find(params[:id])
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = '投稿しました！！'
      redirect_to current_user
    else
      render new_micropost_path
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = '投稿を消去しました。'
    redirect_to request.referer || root_url
  end

  def micropost_params
    params.require(:micropost).permit(:content, :picture, :tag_list)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
        
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
              <%=link_to image_tag(micropost.picture.url,class:'bd-placeholder-img card-img-top' , size: '300x225') ,micropost_path(micropost.id) %>
            <div class="card-body">
              <p class="card-content"><%= micropost.content %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to micropost.user.name, micropost.user ,class: 'btn text-dark ml-2 ml-sm-0',role: 'button'%>
                  
                  <% if current_user?(micropost.user) %>
                    <%= link_to micropost,method: :delete,data: { confirm: "投稿を消去してよろしいですか？" },class: 'btn ml-2 ml-sm-0 ',role: 'button' do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  <% end %>
                  <!--いいね機能を追加-->
                  <span class="float-right ml-2 d-sm-block d-none" id="micropost-<%= micropost.id %>">
                   <%= render "likes/like", micropost: micropost %>
                  </span>
                  <!-- ------------------------------------------------  -->
                </div>
                <span class="ml-4 text-muted  d-sm-block d-none"><%= micropost.created_at.strftime("%m/%d %H:%M") %></span>
              </div>
              <%= render 'shared/tag_list', tag_list: micropost.tag_list %>
            </div>
          </div>
        </div>
        

app/views/microposts/new.html.erb
<% provide(:title,"新規投稿") %>
<div class="text-center">
  <h1 class="font-weight-bold mt-5">新しい投稿</h1>
  <div class="form-group mt-5">
   <%= form_for(@micropost) do |f| %>
   <%= render 'shared/error_messages', model: f.object %>
   <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'  %>
  </span>
   <div class="field">
     <%= f.text_area :content, placeholder: "コメントを入力してください" ,class:"form-area border mt-2", size: "58x8" %><br />
     <%= f.text_field :tag_list, value: @micropost.tag_list.join(","), placeholder: "タグを入力してください" ,class:"form-area border mt-2", size: "58x1" %><br />
   <%= f.submit "投稿する", class: "btn btn-secondary mt-2" %>
   <% end %>
  </div>
</div>
</div>

app/views/microposts/show.html.erb
<div class="container mt-5">
  <div class="row">
        <div class="col-12 text-center">
<%= image_tag @micropost.picture.url, class:'bd-placeholder-img card-img-top' , size: '700x700' if @micropost.picture? %><br/>

<div class= "mt-5">
<%= @micropost.content %><br/>
</div>

<div class= "mt-5">
<%= link_to "戻る", :back ,class: "btn btn-secondary btn-lg" ,tabindex: "-1", role: "button" %>
</div>

</div>
</div>
</div>