config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }


  #get 'users/show'
  resources :users,               only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # deviseコントローラーによる追加
  # devise_for :users, controllers: {
  # sessions: 'users/sessions',
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  # registrations: 'users/registrations'
  # }
end

app/views/layouts/_footer.html.erb
<div class="container pt-5">


    <div class= "text-center">
     <%= link_to "上へ", { anchor: "top" }, class: "btn btn-dark btn-lg" ,tabindex: "-1", role: "button" %><br>
     <%= link_to "HOME", root_path , class: "btn btn-dark btn-lg mt-3" ,tabindex: "-1", role: "button" %>
    </div>


</div>

app/views/layouts/_header.html.erb
<div class="container">

  <div class="row">
    <style>
      #logo {
  float: left;
  margin-right: 10px;
  font-size: 1.7em;
  color: black;
  text-transform: uppercase;
  letter-spacing: -1px;
  padding-top: 9px;
  font-weight: bold;
  &:hover {
    color: white;
    text-decoration: none;
  }


}
    </style>  

    <% if user_signed_in? %>
    <!--ログイン後の画面-->

    <div class="col-md-8">
      <%= link_to "foods app", root_path , id: "logo" %>
    </div>  
    <div class="col-md-1">
      <%= link_to users_path, id: "logo" do %>
       <i class="fas fa-users"></i>
      <% end %>
    </div>

    <div class="col-md-1">
      <%= link_to new_micropost_path, id: "logo" do %>
       <i class="fas fa-paper-plane"></i>
      <% end %>
    </div>

    <div class="dropdown col-md-2">
      <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        メニュー
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <%= link_to "マイページ", user_path(current_user), class: 'dropdown-item' %>
        <%=link_to "編集",edit_user_registration_path, class: 'dropdown-item' %>
        <%= link_to "新規投稿", new_micropost_path, class: 'dropdown-item' %>
        <%= link_to "ユーザー一覧", users_path, class: 'dropdown-item' %>
        <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: 'dropdown-item' %>
        <%= link_to "お問い合わせ", "#", class: 'dropdown-item' %>
      </div>
    </div>
      <div class= "container">
        <%= render 'shared/flash_messages' %>
      </div>

<% else %>
<div class="col-md-10">
      <%= link_to "foods app", root_path , id: "logo" %>
    </div>

<div class="dropdown col-md-2">
  <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    メニュー
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to "新規登録", new_user_registration_path, class: 'dropdown-item' %>
    <%= link_to "ログイン", new_user_session_path, class: 'dropdown-item' %>
    <%= link_to "お問い合わせ", "#", class: 'dropdown-item' %>
  </div>
</div>

  <div class= "container"> 
    <%= render 'shared/flash_messages' %>
  </div>

<%end%>

<p id="top"></p>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--bootstrapの追加-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
　　 <!--開発用デバッグ-->
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>